name: Upload Python Packages

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy-legacy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python for legacy package
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies for legacy package
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build legacy package
      run: python -m build --sdist --wheel --outdir dist/legacy . -c setup_ipython.py
    - name: Publish legacy package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
  
  deploy-new:
    needs: deploy-legacy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python for new package
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies for new package
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build new package
      run: python -m build
    - name: Publish new package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
